version: '3.7'

services:
  orders-server:
    image: mosimaiain/orders-server:prod
    ports:
      - "8081:8080"
    networks:
      - qijani-network
    mem_limit: 100m


  packages-server:
    image: mosimaiain/packages-server:prod
    ports:
      - "8082:8080"
    networks:
      - qijani-network
    mem_limit: 70m

  products-server:
    image: mosimaiain/products-server:prod
    ports:
      - "8083:8080"
    networks:
      - qijani-network
    mem_limit: 100m

  users-server:
    image: mosimaiain/users-server:prod
    ports:
      - "8084:8080"
    networks:
      - qijani-network
    mem_limit: 70m

  reverseproxy-backend:
    image: mosimaiain/reverseproxy-backend:prod
    ports:
      - "8080:80"
    networks:
      - qijani-network
    depends_on:
      - orders-server
      - packages-server
      - products-server
      - users-server
    mem_limit: 50m
  
  reverseproxy:
    platform: linux/amd64
    image: mosimaiain/reverseproxy:prod
    ports:
    - "443:443"
    networks:
      - qijani-network
    depends_on:
      - reverseproxy-backend
  
  qijani-frontend:
    platform: linux/amd64
    image: mosimaiain/qijani-frontend:prod
    ports:
      - "3000:3000"
    mem_limit: 200m
    depends_on:
      - reverseproxy

networks:
  qijani-network:
    driver: bridge