apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-server
  template:
    metadata:
      labels:
        app: orders-server
    spec:
      containers:
        - name: orders-server
          image: mosimaiain/orders-server:prod
          ports:
            - containerPort: 5000
