apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reverseproxy-ingress
spec:
  tls:
  - hosts:
    - qijani.com
    secretName: tls-secret
  rules:
  - host: qijani.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reverseproxy
            port:
              number: 443
