apiVersion: apps/v1
kind: Deployment
metadata:
  name: packages-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: packages-server
  template:
    metadata:
      labels:
        app: packages-server
    spec:
      containers:
        - name: packages-server
          image: mosimaiain/packages-server:prod
          ports:
            - containerPort: 5000
